### ISSUE TITLE
full.json shouldn't have spaces in URLs or empty URLs

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-show-ppp#7]
https://github.com/open-contracting/ocds-show-ppp/blob/gh-pages/example/full.json

**Comment by kindly** [comment]
@jpmckinney this file was generated from a xlsx representation managed by @duncandewhurst and @timgdavies so it should really be fixed there.

**Comment by jpmckinney** [comment]
Where is the XLSX?

**Comment by duncandewhurst** [comment]
Seems like the full.json in this repo was out of sync with the more up to date one in the public-private-partnerships repo which doesn't have spaces in the urls.

I've replaced it here: https://github.com/open-contracting/ocds-show-ppp/pull/8

@jpmckinney any idea why the diff would be so big? I tried ?w=1...

**Comment by jpmckinney** [comment]
Typos had been corrected in public-private-partnerships, and it looks like other additions were made. Anyhow, I don't see an issue with syncing them, so I merged. Thanks!
